### ISSUE TITLE
5.10 שינוי הרשאות של מנהל חנות

### ISSUE THREAD

**Issue by michaelNXT1** [michaelNXT1/SoftwareEngineeringProject2023#32]
מפעילים:
בעל חנות או מנהל חנות בעל הרשאה מתאימה
תנאי התחלה:
למפעיל יש הרשאה מתאימה (הינו בעל חנות או מנהל עם הרשאה).
החנות קיימת.
המפעיל הינו בעל החנות הספציפית שלה אנחנו רוצים לשנות את ההרשאות של מנהל.
המינוי הינו מנהל החנות
המפעיל הינו הממונה על מנהל החנות (הוא הפך אותו למנהל)
פרמטרים:
מ"ז של המפעיל
מ״ז של מנהל החנות
מ"ז של החנות
סוג ההרשאות שנרצה להוסיף
תוצאה:
למנהל החנות יש כעת את ההרשאות שבעל החנות נתן לו.
תנאי סיום:
למנהל החנות יש כעת את ההרשאות שבעל החנות נתן לו.
פעולות:
המפעיל שולח בקשה למערכת השוק להוספת הרשאות למנהל חנות .
מערכת השוק מוודא שהמפעיל הינו בעל חנות ושהמנוי של מנהל החנות אכן קיים.
מערכת השוק בודקת שסט ההרשאות הוא כחלק מסט ההרשאות הקיימות.
נוספו למנהל החנות ההרשאות הרלוונטיות.

**Comment by shoham207** [comment]
חילקתי ל2 פונקציות שונות- אחת של להוסיף הרשאה ואחת של להסיר הרשאה.
